-- Mock events across 6 Italian cities for MVP testing
-- Run AFTER 001_create_events.sql

INSERT INTO events (title, description, category, venue_name, address, location, start_time, end_time, price_info, source_url, source_name, external_id) VALUES

-- MILANO (45.4642, 9.1900)
('Jazz al Blue Note', 'Serata jazz dal vivo con artisti internazionali', 'musica', 'Blue Note Milano', 'Via Borsieri 37, Milano', ST_SetSRID(ST_MakePoint(9.1870, 45.4890), 4326)::geography, NOW() + INTERVAL '1 day', NOW() + INTERVAL '1 day' + INTERVAL '3 hours', '€25', 'https://bluenotemilano.com', 'mock', 'mock-mi-001'),
('Mostra Picasso', 'Retrospettiva dedicata al periodo blu di Picasso', 'cultura', 'Palazzo Reale', 'Piazza del Duomo 12, Milano', ST_SetSRID(ST_MakePoint(9.1905, 45.4633), 4326)::geography, NOW() + INTERVAL '2 days', NOW() + INTERVAL '60 days', '€15', 'https://palazzoreale.it', 'mock', 'mock-mi-002'),
('Mercatino Navigli', 'Mercato vintage e artigianato lungo i Navigli', 'mercato', 'Naviglio Grande', 'Alzaia Naviglio Grande, Milano', ST_SetSRID(ST_MakePoint(9.1680, 45.4510), 4326)::geography, NOW() + INTERVAL '3 days', NOW() + INTERVAL '3 days' + INTERVAL '8 hours', 'Gratuito', 'https://naviglimilano.it', 'mock', 'mock-mi-003'),
('Techno Night', 'DJ set con artisti della scena techno europea', 'nightlife', 'Amnesia Milano', 'Via Forlanini 50, Milano', ST_SetSRID(ST_MakePoint(9.2350, 45.4580), 4326)::geography, NOW() + INTERVAL '4 days', NOW() + INTERVAL '4 days' + INTERVAL '6 hours', '€20', 'https://amnesiamilano.com', 'mock', 'mock-mi-004'),
('Cinema all''aperto: La Dolce Vita', 'Proiezione del capolavoro di Fellini sotto le stelle', 'cinema', 'Parco Sempione', 'Piazza Sempione, Milano', ST_SetSRID(ST_MakePoint(9.1750, 45.4730), 4326)::geography, NOW() + INTERVAL '5 days', NOW() + INTERVAL '5 days' + INTERVAL '3 hours', '€8', 'https://cinemamilano.it', 'mock', 'mock-mi-005'),
('Partita AC Milan vs Inter', 'Derby della Madonnina — Serie A', 'sport', 'Stadio San Siro', 'Via Piccolomini 5, Milano', ST_SetSRID(ST_MakePoint(9.1239, 45.4781), 4326)::geography, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days' + INTERVAL '2 hours', '€45-€120', 'https://acmilan.com', 'mock', 'mock-mi-006'),
('Food Festival Milano', 'Street food da tutta Italia con cooking show', 'food', 'Fiera Milano City', 'Viale Scarampo, Milano', ST_SetSRID(ST_MakePoint(9.1460, 45.4740), 4326)::geography, NOW() + INTERVAL '7 days', NOW() + INTERVAL '9 days', '€10', 'https://fieramilano.it', 'mock', 'mock-mi-007'),
('Romeo e Giulietta', 'Adattamento moderno del classico shakespeariano', 'teatro', 'Teatro alla Scala', 'Via Filodrammatici 2, Milano', ST_SetSRID(ST_MakePoint(9.1893, 45.4676), 4326)::geography, NOW() + INTERVAL '8 days', NOW() + INTERVAL '8 days' + INTERVAL '3 hours', '€30-€80', 'https://teatroallascala.org', 'mock', 'mock-mi-008'),
('Yoga nel Parco', 'Sessione di yoga gratuita per tutti i livelli', 'sport', 'Parco Sempione', 'Piazza Sempione, Milano', ST_SetSRID(ST_MakePoint(9.1740, 45.4720), 4326)::geography, NOW() + INTERVAL '2 days', NOW() + INTERVAL '2 days' + INTERVAL '1 hour', 'Gratuito', 'https://yogamilano.it', 'mock', 'mock-mi-009'),

-- ROMA (41.9028, 12.4964)
('Concerto al Colosseo', 'Orchestra sinfonica all''aperto con vista Colosseo', 'musica', 'Parco del Celio', 'Via del Parco del Celio, Roma', ST_SetSRID(ST_MakePoint(12.4922, 41.8892), 4326)::geography, NOW() + INTERVAL '2 days', NOW() + INTERVAL '2 days' + INTERVAL '2 hours', '€35', 'https://romaeventi.it', 'mock', 'mock-rm-001'),
('Mostra Caravaggio', 'Le opere romane di Caravaggio in una mostra unica', 'cultura', 'Galleria Borghese', 'Piazzale Scipione Borghese 5, Roma', ST_SetSRID(ST_MakePoint(12.4922, 41.9142), 4326)::geography, NOW() + INTERVAL '1 day', NOW() + INTERVAL '90 days', '€18', 'https://galleriaborghese.it', 'mock', 'mock-rm-002'),
('Mercato Porta Portese', 'Il mercato delle pulci più famoso d''Italia', 'mercato', 'Porta Portese', 'Via Portuense, Roma', ST_SetSRID(ST_MakePoint(12.4730, 41.8780), 4326)::geography, NOW() + INTERVAL '5 days', NOW() + INTERVAL '5 days' + INTERVAL '6 hours', 'Gratuito', 'https://portaportese.it', 'mock', 'mock-rm-003'),
('Notte Bianca Trastevere', 'Musica, cibo e arte fino all''alba in Trastevere', 'nightlife', 'Trastevere', 'Piazza di Santa Maria in Trastevere, Roma', ST_SetSRID(ST_MakePoint(12.4694, 41.8895), 4326)::geography, NOW() + INTERVAL '4 days', NOW() + INTERVAL '5 days', 'Gratuito', 'https://romatoday.it', 'mock', 'mock-rm-004'),
('Festival del Cinema Indipendente', 'Proiezioni di film indipendenti italiani ed europei', 'cinema', 'Cinema Farnese', 'Piazza Campo de'' Fiori 56, Roma', ST_SetSRID(ST_MakePoint(12.4720, 41.8956), 4326)::geography, NOW() + INTERVAL '3 days', NOW() + INTERVAL '5 days', '€12', 'https://cinemafarnese.it', 'mock', 'mock-rm-005'),
('Roma-Lazio Derby', 'Derby della Capitale — Serie A', 'sport', 'Stadio Olimpico', 'Viale dei Gladiatori, Roma', ST_SetSRID(ST_MakePoint(12.4548, 41.9340), 4326)::geography, NOW() + INTERVAL '7 days', NOW() + INTERVAL '7 days' + INTERVAL '2 hours', '€40-€100', 'https://asroma.com', 'mock', 'mock-rm-006'),
('Carbonara Day', 'Degustazione e gara di carbonara tra ristoranti romani', 'food', 'Testaccio', 'Piazza Testaccio, Roma', ST_SetSRID(ST_MakePoint(12.4756, 41.8768), 4326)::geography, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days' + INTERVAL '5 hours', '€15', 'https://romatoday.it', 'mock', 'mock-rm-007'),
('Otello al Globe Theatre', 'Shakespeare nell''anfiteatro all''aperto di Villa Borghese', 'teatro', 'Globe Theatre Roma', 'Largo Aqua Felix, Roma', ST_SetSRID(ST_MakePoint(12.4880, 41.9170), 4326)::geography, NOW() + INTERVAL '3 days', NOW() + INTERVAL '3 days' + INTERVAL '3 hours', '€20', 'https://globetheatreroma.com', 'mock', 'mock-rm-008'),

-- TORINO (45.0703, 7.6869)
('Torino Jazz Festival', 'Festival jazz con artisti da tutto il mondo', 'musica', 'Piazza San Carlo', 'Piazza San Carlo, Torino', ST_SetSRID(ST_MakePoint(7.6830, 45.0680), 4326)::geography, NOW() + INTERVAL '3 days', NOW() + INTERVAL '5 days', 'Gratuito', 'https://torinojazz.it', 'mock', 'mock-to-001'),
('Museo Egizio Notte', 'Visita notturna al Museo Egizio con guida speciale', 'cultura', 'Museo Egizio', 'Via Accademia delle Scienze 6, Torino', ST_SetSRID(ST_MakePoint(7.6843, 45.0685), 4326)::geography, NOW() + INTERVAL '4 days', NOW() + INTERVAL '4 days' + INTERVAL '3 hours', '€20', 'https://museoegizio.it', 'mock', 'mock-to-002'),
('Gran Balon', 'Mercato antiquariato più grande del Piemonte', 'mercato', 'Piazza della Repubblica', 'Piazza della Repubblica, Torino', ST_SetSRID(ST_MakePoint(7.6800, 45.0770), 4326)::geography, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days' + INTERVAL '7 hours', 'Gratuito', 'https://balon.it', 'mock', 'mock-to-003'),
('Murazzi Night', 'Serata elettronica lungo il Po', 'nightlife', 'Murazzi del Po', 'Murazzi del Po, Torino', ST_SetSRID(ST_MakePoint(7.6940, 45.0620), 4326)::geography, NOW() + INTERVAL '5 days', NOW() + INTERVAL '6 days', '€15', 'https://torinotoday.it', 'mock', 'mock-to-004'),
('Cinema sotto le Stelle', 'Rassegna cinematografica estiva', 'cinema', 'Parco del Valentino', 'Corso Massimo d''Azeglio, Torino', ST_SetSRID(ST_MakePoint(7.6870, 45.0570), 4326)::geography, NOW() + INTERVAL '2 days', NOW() + INTERVAL '2 days' + INTERVAL '3 hours', '€7', 'https://torinotoday.it', 'mock', 'mock-to-005'),
('Cioccolatò', 'Festival del cioccolato artigianale piemontese', 'food', 'Piazza Vittorio Veneto', 'Piazza Vittorio Veneto, Torino', ST_SetSRID(ST_MakePoint(7.6960, 45.0650), 4326)::geography, NOW() + INTERVAL '8 days', NOW() + INTERVAL '10 days', 'Gratuito', 'https://cioccolato.it', 'mock', 'mock-to-006'),
('Juve vs Napoli', 'Big match Serie A', 'sport', 'Allianz Stadium', 'Corso Gaetano Scirea 50, Torino', ST_SetSRID(ST_MakePoint(7.6412, 45.1096), 4326)::geography, NOW() + INTERVAL '7 days', NOW() + INTERVAL '7 days' + INTERVAL '2 hours', '€50-€150', 'https://juventus.com', 'mock', 'mock-to-007'),

-- FIRENZE (43.7696, 11.2558)
('Estate Fiorentina', 'Concerti live in piazza all''aperto', 'musica', 'Piazza della Signoria', 'Piazza della Signoria, Firenze', ST_SetSRID(ST_MakePoint(11.2558, 43.7696), 4326)::geography, NOW() + INTERVAL '2 days', NOW() + INTERVAL '2 days' + INTERVAL '4 hours', '€10', 'https://firenzetoday.it', 'mock', 'mock-fi-001'),
('Uffizi di Notte', 'Apertura serale straordinaria degli Uffizi', 'cultura', 'Galleria degli Uffizi', 'Piazzale degli Uffizi, Firenze', ST_SetSRID(ST_MakePoint(11.2558, 43.7678), 4326)::geography, NOW() + INTERVAL '4 days', NOW() + INTERVAL '4 days' + INTERVAL '4 hours', '€12', 'https://uffizi.it', 'mock', 'mock-fi-002'),
('Mercato di San Lorenzo', 'Mercato storico con prodotti tipici toscani', 'mercato', 'Mercato Centrale', 'Piazza del Mercato Centrale, Firenze', ST_SetSRID(ST_MakePoint(11.2535, 43.7760), 4326)::geography, NOW() + INTERVAL '1 day', NOW() + INTERVAL '1 day' + INTERVAL '10 hours', 'Gratuito', 'https://mercatocentrale.it', 'mock', 'mock-fi-003'),
('Bistecca Festival', 'Celebrazione della bistecca alla fiorentina', 'food', 'Piazza Santo Spirito', 'Piazza Santo Spirito, Firenze', ST_SetSRID(ST_MakePoint(11.2490, 43.7668), 4326)::geography, NOW() + INTERVAL '5 days', NOW() + INTERVAL '7 days', '€20', 'https://firenzetoday.it', 'mock', 'mock-fi-004'),
('Divina Commedia in scena', 'Spettacolo teatrale itinerante per le vie del centro', 'teatro', 'Centro Storico Firenze', 'Piazza del Duomo, Firenze', ST_SetSRID(ST_MakePoint(11.2560, 43.7731), 4326)::geography, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days' + INTERVAL '2 hours', '€18', 'https://teatrofirenze.it', 'mock', 'mock-fi-005'),
('Fiorentina vs Roma', 'Serie A al Franchi', 'sport', 'Stadio Artemio Franchi', 'Viale Manfredo Fanti 4, Firenze', ST_SetSRID(ST_MakePoint(11.2828, 43.7808), 4326)::geography, NOW() + INTERVAL '8 days', NOW() + INTERVAL '8 days' + INTERVAL '2 hours', '€35-€80', 'https://acffiorentina.com', 'mock', 'mock-fi-006'),

-- NAPOLI (40.8518, 14.2681)
('Napoli Pizza Village', 'Il più grande festival della pizza al mondo', 'food', 'Lungomare Caracciolo', 'Via Partenope, Napoli', ST_SetSRID(ST_MakePoint(14.2470, 40.8300), 4326)::geography, NOW() + INTERVAL '3 days', NOW() + INTERVAL '6 days', 'Gratuito', 'https://pizzavillage.it', 'mock', 'mock-na-001'),
('Concerto Pino Daniele Tribute', 'Omaggio al grande artista napoletano', 'musica', 'Piazza del Plebiscito', 'Piazza del Plebiscito, Napoli', ST_SetSRID(ST_MakePoint(14.2488, 40.8359), 4326)::geography, NOW() + INTERVAL '5 days', NOW() + INTERVAL '5 days' + INTERVAL '3 hours', 'Gratuito', 'https://napolitoday.it', 'mock', 'mock-na-002'),
('Mostra Pompei Segreta', 'Reperti inediti dagli scavi di Pompei', 'cultura', 'MANN - Museo Archeologico', 'Piazza Museo 19, Napoli', ST_SetSRID(ST_MakePoint(14.2504, 40.8535), 4326)::geography, NOW() + INTERVAL '1 day', NOW() + INTERVAL '120 days', '€16', 'https://museoarcheologiconapoli.it', 'mock', 'mock-na-003'),
('Notte a Spaccanapoli', 'Musica e spettacoli nel cuore di Napoli', 'nightlife', 'Spaccanapoli', 'Via Benedetto Croce, Napoli', ST_SetSRID(ST_MakePoint(14.2530, 40.8490), 4326)::geography, NOW() + INTERVAL '4 days', NOW() + INTERVAL '5 days', 'Gratuito', 'https://napolitoday.it', 'mock', 'mock-na-004'),
('Napoli vs Milan', 'Big match Serie A', 'sport', 'Stadio Diego Armando Maradona', 'Piazzale Vincenzo Tecchio, Napoli', ST_SetSRID(ST_MakePoint(14.1930, 40.8280), 4326)::geography, NOW() + INTERVAL '7 days', NOW() + INTERVAL '7 days' + INTERVAL '2 hours', '€40-€100', 'https://sscnapoli.it', 'mock', 'mock-na-005'),
('Eduardo De Filippo: Natale in Casa Cupiello', 'Classico del teatro napoletano', 'teatro', 'Teatro San Carlo', 'Via San Carlo 98, Napoli', ST_SetSRID(ST_MakePoint(14.2497, 40.8375), 4326)::geography, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days' + INTERVAL '3 hours', '€25-€60', 'https://teatrosancarlo.it', 'mock', 'mock-na-006'),

-- BOLOGNA (44.4949, 11.3426)
('Bologna Jazz Festival', 'Rassegna jazz nelle piazze del centro', 'musica', 'Piazza Maggiore', 'Piazza Maggiore, Bologna', ST_SetSRID(ST_MakePoint(11.3430, 44.4938), 4326)::geography, NOW() + INTERVAL '2 days', NOW() + INTERVAL '4 days', 'Gratuito', 'https://bolognajazz.it', 'mock', 'mock-bo-001'),
('Arte Fiera Bologna', 'Fiera internazionale d''arte contemporanea', 'cultura', 'BolognaFiere', 'Piazza Costituzione 6, Bologna', ST_SetSRID(ST_MakePoint(11.3260, 44.5100), 4326)::geography, NOW() + INTERVAL '5 days', NOW() + INTERVAL '7 days', '€14', 'https://artefiera.it', 'mock', 'mock-bo-002'),
('Mercato delle Erbe Speciale', 'Degustazione prodotti emiliani al mercato coperto', 'food', 'Mercato delle Erbe', 'Via Ugo Bassi 25, Bologna', ST_SetSRID(ST_MakePoint(11.3390, 44.4950), 4326)::geography, NOW() + INTERVAL '3 days', NOW() + INTERVAL '3 days' + INTERVAL '6 hours', '€5', 'https://bolognawelcome.it', 'mock', 'mock-bo-003'),
('Notte Rosa Bolognese', 'Serate nei locali del centro con DJ e live music', 'nightlife', 'Via del Pratello', 'Via del Pratello, Bologna', ST_SetSRID(ST_MakePoint(11.3340, 44.4936), 4326)::geography, NOW() + INTERVAL '4 days', NOW() + INTERVAL '5 days', 'Gratuito', 'https://bolognawelcome.it', 'mock', 'mock-bo-004'),
('Il Cinemino Open Air', 'Film d''autore all''aperto in Piazza Maggiore', 'cinema', 'Piazza Maggiore', 'Piazza Maggiore, Bologna', ST_SetSRID(ST_MakePoint(11.3428, 44.4940), 4326)::geography, NOW() + INTERVAL '6 days', NOW() + INTERVAL '6 days' + INTERVAL '3 hours', 'Gratuito', 'https://cinetecadibologna.it', 'mock', 'mock-bo-005'),
('Bologna FC vs Inter', 'Serie A al Dall''Ara', 'sport', 'Stadio Renato Dall''Ara', 'Via Andrea Costa 174, Bologna', ST_SetSRID(ST_MakePoint(11.3100, 44.4923), 4326)::geography, NOW() + INTERVAL '8 days', NOW() + INTERVAL '8 days' + INTERVAL '2 hours', '€30-€70', 'https://bolognafc.it', 'mock', 'mock-bo-006'),
('Vintage Market Bolognina', 'Mercatino vintage nel quartiere Bolognina', 'mercato', 'Piazza dell''Unità', 'Piazza dell''Unità, Bologna', ST_SetSRID(ST_MakePoint(11.3500, 44.5050), 4326)::geography, NOW() + INTERVAL '5 days', NOW() + INTERVAL '5 days' + INTERVAL '8 hours', 'Gratuito', 'https://bolognawelcome.it', 'mock', 'mock-bo-007');
